<?php
    include('config/constants.php');
    if(isset($_GET['p_id'])){
        //get the p_id value
        $p_id_url = $_GET['p_id'];

        $conn = mysqli_connect(LOCALHOST, DB_USERNAME, DB_PASSWORD) or die(mysqli_error());
        $db_select = mysqli_select_db($conn, DB_NAME) or die(mysqli_error());

        //sql query to get the values from database
        $sql = "SELECT * FROM patient
                WHERE p_id=$p_id_url";

        $res = mysqli_query($conn, $sql);
        
        //to check execution of query
        if($res == true){
            //get the value from database
            //value in array format
            $row = mysqli_fetch_assoc($res);
            //print_r($row);

            //create indvidual variable to save the data
            $p_name=$row['p_name'];
            $age=$row['p_age'];
            $address=$row['p_address'];
            $contact=$row['p_contact'];
    
        }
        $sql2 = "SELECT * FROM report WHERE p_id=$p_id_url";
        $res2 = mysqli_query($conn, $sql2);

        if($res2 == true){
            $row2 = mysqli_fetch_assoc($res2);
            $report_id=$row2['report_id'];
            $result=$row2['result'];
            $remarks=$row2['remarks'];
            $date=$row2['date_of_report'];
        }
    }
    else{
        header('location:'.SITEURL.'patient.php');
    }

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Go Corona Go</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <link rel="stylesheet" href="<?php echo SITEURL;?>css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

</head>
<body>
    <div class="main-bg">
    <div class="report">
        <div class="row report-head">
            <div class="col-lg-2">
                <img class="img-responsive" src="images/logo.png" alt="logo">
            </div>
            <div class="col-lg-10 head-block">
                <h1 class="mgn-r">Go Corona Go HMS</h1>
                <p class="mgn-r"><b><i>199/2A, Street No. 12, Daulat Nagar, New Delhi, IN</i></b></p>
                <p class="mgn-r"><b>Email: </b>info@gcghms.com</p>
                <p class="mgn-r"><b>Visit: </b>www.gocoronago.com</p>
            </div>
        </div>
        <hr>
        <div class="report-details">
            <div><h3>LABORATORY TEST REPORT</h3></div>
            <div class="row personal-data">
                <div class="col-lg-8">
                    <p><b>Reg. No.: </b>REPN00<?php echo $report_id; ?></p>
                    <p><b>Name : </b><?php echo $p_name; ?></p>
                    <p><b>Phone No.: </b><?php echo $contact; ?></p>
                    <p><b>Address : </b><?php echo $address; ?></p>
                </div>
                <div class="col-lg-4">
                    <p><b>Report Date: </b><?php echo $date; ?></p>
                    <p><b>Age : </b><?php echo $age; ?> Years</p>
                    <p><b>Test Type : </b>Swab</p>
                    <p><b>Test Center : </b>Delhi, IN</p>
                </div>
            </div>
            <hr>
            <h4><u>COVID-19 TESTING SARS-CoV-2 RNA</u> </h4>
            SARS-CoV-2
            <p><b>Method : </b>Real Time RT-PCR</p>
            <div class="report-result">
                <p><b>Result : </b><?php echo $result; ?></p>
                <p><b>Remarks : </b><?php echo $remarks; ?></p>
            </div>
        </div>
        <div class="footer-report">
            This one-time report is generated by <a href=" www.gcghms.com"> www.gcghms.com</a>
            <p>All rights reserved, ©️ Go Corona Go, HMS</p>
        </div>
    </div>
    
    </div>
    
</body>
</html>